import type { Recipe } from './types'

const ts = new Date().toISOString()

export const DEMO_RECIPES: Recipe[] = [
  {
    id: 'demo-1',
    user_id: 'demo',
    name: 'Golden Hour Street',
    film_simulation: 'classic_negative',
    dynamic_range: 'DR200',
    grain_effect: 'Weak Large',
    color_chrome_effect: 'Strong',
    color_chrome_effect_blue: 'Off',
    white_balance: 'Daylight',
    highlight: -1,
    shadow: 1,
    color: 2,
    sharpness: -1,
    noise_reduction: -3,
    clarity: 2,
    wb_red_shift: 0,
    wb_blue_shift: 0,
    iso: 'Auto up to ISO 6400',
    exposure_compensation: '+1/3',
    camera_body: 'X-T5',
    is_favorite: true,
    notes: 'Perfect for late afternoon. Push shadows to retain detail in harsh light.',
    created_at: ts,
    updated_at: ts,
  },
  {
    id: 'demo-2',
    user_id: 'demo',
    name: 'Moody Velvia Landscape',
    film_simulation: 'velvia',
    dynamic_range: 'DR400',
    grain_effect: 'Off',
    color_chrome_effect: 'Weak',
    color_chrome_effect_blue: 'Weak',
    white_balance: 'Shade',
    highlight: -2,
    shadow: 2,
    color: 3,
    sharpness: 1,
    noise_reduction: -2,
    clarity: 3,
    wb_red_shift: 0,
    wb_blue_shift: 0,
    iso: 'ISO 160',
    exposure_compensation: '-1/3',
    camera_body: 'X-T5',
    is_favorite: true,
    notes: 'Best used on overcast days for rich, punchy color without blowing highlights.',
    created_at: ts,
    updated_at: ts,
  },
  {
    id: 'demo-3',
    user_id: 'demo',
    name: 'Silver & Grain Acros',
    film_simulation: 'acros',
    dynamic_range: 'DR200',
    grain_effect: 'Strong Small',
    color_chrome_effect: 'Off',
    color_chrome_effect_blue: 'Off',
    white_balance: 'Auto (AWB)',
    highlight: 0,
    shadow: -1,
    color: 0,
    sharpness: 2,
    noise_reduction: -4,
    clarity: 0,
    wb_red_shift: 0,
    wb_blue_shift: 0,
    iso: 'ISO 1600',
    exposure_compensation: '0',
    camera_body: 'X100VI',
    is_favorite: false,
    notes: 'High ISO grain gives a real film feel. Great for café interiors.',
    created_at: ts,
    updated_at: ts,
  },
  {
    id: 'demo-4',
    user_id: 'demo',
    name: 'Eterna Cinema Fade',
    film_simulation: 'eterna',
    dynamic_range: 'Auto',
    grain_effect: 'Weak Small',
    color_chrome_effect: 'Off',
    color_chrome_effect_blue: 'Off',
    white_balance: 'Auto Ambience Priority',
    highlight: -2,
    shadow: -1,
    color: -1,
    sharpness: -2,
    noise_reduction: 0,
    clarity: -2,
    wb_red_shift: 0,
    wb_blue_shift: 0,
    iso: 'Auto up to ISO 3200',
    exposure_compensation: '+2/3',
    camera_body: 'X-S20',
    is_favorite: false,
    notes: 'Cinematic, desaturated look. Pair with warm practical lighting.',
    created_at: ts,
    updated_at: ts,
  },
  {
    id: 'demo-5',
    user_id: 'demo',
    name: 'Classic Chrome Street',
    film_simulation: 'classic_chrome',
    dynamic_range: 'DR200',
    grain_effect: 'Weak Large',
    color_chrome_effect: 'Weak',
    color_chrome_effect_blue: 'Off',
    white_balance: 'Auto (AWB)',
    highlight: -1,
    shadow: 0,
    color: -1,
    sharpness: 0,
    noise_reduction: -2,
    clarity: 1,
    wb_red_shift: 0,
    wb_blue_shift: 0,
    iso: 'Auto up to ISO 6400',
    exposure_compensation: '0',
    camera_body: 'X-Pro3',
    is_favorite: false,
    notes: 'Muted, documentary feel reminiscent of Kodachrome.',
    created_at: ts,
    updated_at: ts,
  },
  {
    id: 'demo-6',
    user_id: 'demo',
    name: 'Nostalgic Warm Portraits',
    film_simulation: 'nostalgic_neg',
    dynamic_range: 'DR200',
    grain_effect: 'Weak Large',
    color_chrome_effect: 'Off',
    color_chrome_effect_blue: 'Off',
    white_balance: 'Auto Ambience Priority',
    highlight: 0,
    shadow: 1,
    color: 1,
    sharpness: -1,
    noise_reduction: -1,
    clarity: 0,
    wb_red_shift: 0,
    wb_blue_shift: 0,
    iso: 'Auto up to ISO 3200',
    exposure_compensation: '+1/3',
    camera_body: 'X-T5',
    is_favorite: false,
    notes: 'Warm, creamy skin tones. Add slight overexposure for that airy feel.',
    created_at: ts,
    updated_at: ts,
  },
]
